credentials:
  usernames:
    abc:
      email: Krysenjo2266@gmail.com
      name: abc
      password: $2b$12$33ViQ.PEXSzsnN/tpZnMxe5GrZtCZokhr6RppY/fGhUGC.F9mEj2y
cookie:
  expiry_days: 0
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - Krysenjo2266@gmail.com